apiVersion: v1
kind: Service
metadata:
  labels:
    name: gridvo-mqtt-admin
  name: gridvo-mqtt-admin
  namespace: gridvo
spec:
  selector:
    name: gridvo-mqtt-admin
  type: NodePort
  ports:
     - port: 80
       targetPort: 9191
       nodePort: 31019
