apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: gridvo-mqtt-admin
  name: gridvo-mqtt-admin
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gridvo-mqtt-admin
    spec:
      containers:
      - name: gridvo-mqtt-admin
        image: 10.0.3.31:5000/gridvo/gridvo-mqtt-admin:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 9191
        env:
        - name: MONGODB_SERVICE_HOST
          value: "mongodb"
        - name: MONGODB_SERVICE_PORT
          value: "27017"
        - name: IS_DEBUG
          value: "true"
             
